services:
  vaultlight:
    build: .
    container_name: vaultlight
    ports:
      - "4311:4311"
    env_file:
      - backend/.env
    environment:
      PORT: "4311"
      DATABASE_PATH: "/app/data/database.db"
    volumes:
      - ./storage/uploads:/app/uploads
      - ./storage/database:/app/data
    user: "0:0"
    restart: unless-stopped

